import {
    product,
    product2,
    product3,
    product4,
    product5,
    product6,
    product7,
    product8,
    product9,
    product10,
    product11,
    product12,
    product13,
    product14,
    product15,
    product16,
    fiveStar,
    fourHalfStar,
    fourStar,
    threeStar,
    person1,
    person2,
    person3,
    hero1,
    hero2,
    hero3,
    hero4,
    hero5,
    playStation,
    attractiveWoman,
    speaker,
    gucciPerfume,
} from "../assets/images";

import {
    FaBagShopping,
    FaCamera,
    FaCartShopping,
    FaComputer,
    FaDollarSign,
    FaGamepad,
    FaHeadphones,
    FaHeadset,
    FaHeart,
    FaInstagram,
    FaLinkedinIn,
    FaMobileScreen,
    FaRegCircleCheck,
    FaRegHeart,
    FaSackDollar,
    FaSquareCheck,
    FaStore,
    FaTruckFast,
    FaXTwitter,
} from "react-icons/fa6";

import { GiWatch } from "react-icons/gi";

export const navLinks = [
    { href: "/", label: "Home" },
    { href: "/products", label: "Products" },
    { href: "/contact", label: "Contact" },
    { href: "/about", label: "About" },
];

export const navIconLinks = [
    {
        href: "/wishlist",
        label: "Wishlist",
        icon: <FaRegHeart className="text-2xl" />,
        storageName: "wishlistItems",
    },
    {
        href: "/cart",
        label: "Cart",
        icon: <FaCartShopping className="text-2xl" />,
        storageName: "cartItems",
    },
];

export const sideLinks = [
    { label: "Women's Fashion", category: "Women's Fashion" },
    { label: "Men's Fashion", category: "Men's Fashion" },
    { label: "Electronics", category: "Electronics" },
    { label: "Home & Lifestyle", category: "Home & Lifestyle" },
    { label: "Medicine", category: "Medicine" },
    { label: "Sports & Outdoor", category: "Sports & Outdoor" },
    { label: "Baby’s & Toys", category: "Baby’s & Toys" },
    { label: "Groceries & Pets", category: "Groceries & Pets" },
    { label: "Health & Beauty", category: "Health & Beauty" },
];
export const productCategories = [
    { label: "Flash Sales", category: "Flash Sales" },
    { label: "Best Selling Products", category: "Best Selling Products" },
    { label: "Women's Fashion", category: "Women's Fashion" },
    { label: "Men's Fashion", category: "Men's Fashion" },
    { label: "Electronics", category: "Electronics" },
    { label: "Phones", category: "Phones" },
    { label: "Computers", category: "Computers" },
    { label: "SmartWatch", category: "SmartWatch" },
    { label: "Camera", category: "Camera" },
    { label: "HeadPhones", category: "HeadPhones" },
    { label: "Gaming", category: "Gaming" },
    { label: "Home & Lifestyle", category: "Home & Lifestyle" },
    { label: "Medicine", category: "Medicine" },
    { label: "Sports & Outdoor", category: "Sports & Outdoor" },
    { label: "Baby’s & Toys", category: "Baby's & Toys" },
    { label: "Groceries & Pets", category: "Groceries & Pets" },
    { label: "Health & Beauty", category: "Health & Beauty" },
];

export const HeroData = [
    { title: "iPhone 14 ", voucher: 10, img: hero1 },
    { title: "CANON Camera ", voucher: 25, img: hero2 },
    { title: "BOSE Headphone ", voucher: 40, img: hero3 },
    { title: "Sony Gamepad ", voucher: 50, img: hero4 },
    { title: "ASUS Laptop", voucher: 15, img: hero5 },
];

export const NewArrivalData = [
    {
        title: "PlayStation 5",
        description: "Black and White version of the PS5 coming out on sale.",
        img: playStation,
    },
    {
        title: "Women’s Collections",
        description: "Featured woman collections that give you another vibe.",
        img: attractiveWoman,
    },
    {
        title: "Speakers",
        description: "Amazon wireless speakers.",
        img: speaker,
    },
    {
        title: "Perfume",
        description: "Gucci Intense Oud Edp",
        img: gucciPerfume,
    },
];

export const ProductData = {
    flashSales: [
        {
            id: 1,
            productName: "HAVIT HV-G92 Gamepad",
            productImage: product,
            currentPrice: "$120",
            originalPrice: "$160",
            rating: fiveStar,
            rateCount: "88",
            discountPercentage: "-40%",
            quantity: 1,
            subTotal: 120,
        },
        {
            id: 2,
            productName: "AK-900 Wired Keyboard",
            productImage: product2,
            currentPrice: "$960",
            originalPrice: "$1160",
            rating: fourStar,
            rateCount: "75",
            discountPercentage: "-35%",
            quantity: 1,
            subTotal: 960,
        },
        {
            id: 3,
            productName: "IPS LCD Gaming Monitor",
            productImage: product3,
            currentPrice: "$370",
            originalPrice: "$400",
            rating: fiveStar,
            rateCount: "99",
            discountPercentage: "-40%",
            quantity: 1,
            subTotal: 370,
        },
        {
            id: 4,
            productName: "S-Series Comfort Chair ",
            productImage: product4,
            currentPrice: "$375",
            originalPrice: "$400",
            rating: fourHalfStar,
            rateCount: "99",
            discountPercentage: "-25%",
            quantity: 1,
            subTotal: 375,
        },
        {
            id: 55,
            productName: "HAVIT HV-G92 Gamepad",
            productImage: product,
            currentPrice: "$120",
            originalPrice: "$160",
            rating: fiveStar,
            rateCount: "88",
            discountPercentage: "-40%",
            quantity: 1,
            subTotal: 120,
        },
        {
            id: 66,
            productName: "AK-900 Wired Keyboard",
            productImage: product2,
            currentPrice: "$960",
            originalPrice: "$1160",
            rating: fourStar,
            rateCount: "75",
            discountPercentage: "-35%",
            quantity: 1,
            subTotal: 960,
        },
        {
            id: 377,
            productName: "IPS LCD Gaming Monitor",
            productImage: product3,
            currentPrice: "$370",
            originalPrice: "$400",
            rating: fiveStar,
            rateCount: "99",
            discountPercentage: "-40%",
            quantity: 1,
            subTotal: 370,
        },
        {
            id: 88,
            productName: "S-Series Comfort Chair ",
            productImage: product4,
            currentPrice: "$375",
            originalPrice: "$400",
            rating: fourHalfStar,
            rateCount: "99",
            discountPercentage: "-25%",
            quantity: 1,
            subTotal: 375,
        },
    ],
    browseByCategory: [
        {
            categoryName: "Phones",
            categoryImage: <FaMobileScreen className="text-3xl" />,
        },
        {
            categoryName: "Computers",
            categoryImage: <FaComputer className="text-3xl" />,
        },
        {
            categoryName: "SmartWatch",
            categoryImage: <GiWatch className="text-3xl" />,
        },
        {
            categoryName: "Camera",
            categoryImage: <FaCamera className="text-3xl" />,
        },
        {
            categoryName: "HeadPhones",
            categoryImage: <FaHeadphones className="text-3xl" />,
        },
        {
            categoryName: "Gaming",
            categoryImage: <FaGamepad className="text-3xl" />,
        },
    ],
    bestSellingProducts: [
        {
            id: 5,
            productName: "The north coat",
            productImage: product5,
            currentPrice: "$260",
            originalPrice: "",
            rating: fiveStar,
            rateCount: "65",
            discountPercentage: "",
            quantity: 1,
            subTotal: 260,
        },
        {
            id: 6,
            productName: "Gucci duffle bag",
            productImage: product6,
            currentPrice: "$960",
            originalPrice: "",
            rating: fourHalfStar,
            rateCount: "65",
            discountPercentage: "",
            quantity: 1,
            subTotal: 960,
        },
        {
            id: 7,
            productName: "RGB liquid CPU Cooler",
            productImage: product7,
            currentPrice: "$160",
            originalPrice: "",
            rating: fourHalfStar,
            rateCount: "65",
            discountPercentage: "",
            quantity: 1,
            subTotal: 160,
        },
        {
            id: 8,
            productName: "Small BookSelf",
            productImage: product8,
            currentPrice: "$360",
            originalPrice: "",
            rating: fiveStar,
            rateCount: "65",
            discountPercentage: "",
            quantity: 1,
            subTotal: 360,
        },
    ],
    exploreOurProducts: [
        {
            id: 9,
            productName: "Breed Dry Dog Food",
            productImage: product9,
            currentPrice: "$100",
            originalPrice: "",
            rating: threeStar,
            rateCount: "35",
            discountPercentage: "",
            quantity: 1,
            subTotal: 100,
        },
        {
            id: 10,
            productName: "CANON EOS DSLR Camera",
            productImage: product10,
            currentPrice: "$360",
            originalPrice: "",
            rating: fourStar,
            rateCount: "95",
            discountPercentage: "",
            quantity: 1,
            subTotal: 360,
        },
        {
            id: 11,
            productName: "ASUS FHD Gaming Laptop",
            productImage: product11,
            currentPrice: "$700",
            originalPrice: "",
            rating: fiveStar,
            rateCount: "325",
            discountPercentage: "",
            quantity: 1,
            subTotal: 700,
        },
        {
            id: 12,
            productName: "Curology Product Set ",
            productImage: product12,
            currentPrice: "$500",
            originalPrice: "",
            rating: fourStar,
            rateCount: "145",
            discountPercentage: "",
            quantity: 1,
            subTotal: 500,
        },
        {
            id: 13,
            productName: "Kids Electric Car",
            productImage: product13,
            currentPrice: "$960",
            originalPrice: "",
            rating: fiveStar,
            rateCount: "65",
            discountPercentage: "",
            quantity: 1,
            subTotal: 960,
        },
        {
            id: 14,
            productName: "Jr. Zoom Soccer Cleats",
            productImage: product14,
            currentPrice: "$1160",
            originalPrice: "",
            rating: fiveStar,
            rateCount: "35",
            discountPercentage: "",
            quantity: 1,
            subTotal: 1160,
        },
        {
            id: 15,
            productName: "GP11 Shooter USB Gamepad",
            productImage: product15,
            currentPrice: "$660",
            originalPrice: "",
            rating: fourHalfStar,
            rateCount: "55",
            discountPercentage: "",
            quantity: 1,
            subTotal: 660,
        },
        {
            id: 16,
            productName: "Quilted Satin Jacket",
            productImage: product16,
            currentPrice: "$660",
            originalPrice: "",
            rating: fourHalfStar,
            rateCount: "55",
            discountPercentage: "",
            quantity: 1,
            subTotal: 660,
        },
    ],
};

export const shopInfo = [
    {
        label: "shop",
        shopInfoIcon: <FaStore className="fill-white text-2xl" />,
        shopInfoNumber: "10.5k ",
        shopInfoDescription: "Active sellers in our site",
    },
    {
        label: "moneySign",
        shopInfoIcon: <FaDollarSign className="fill-white text-2xl" />,
        shopInfoNumber: "33k",
        shopInfoDescription: "Monthly Product Sales",
    },
    {
        label: "shoppingBag",
        shopInfoIcon: <FaBagShopping className="fill-white text-2xl" />,
        shopInfoNumber: "45.5k",
        shopInfoDescription: "Active customers in our site",
    },
    {
        label: "moneyBag",
        shopInfoIcon: <FaSackDollar className="fill-white text-2xl" />,
        shopInfoNumber: "25k",
        shopInfoDescription: "Anual gross sales in our site",
    },
];
export const services = [
    {
        serviceImg: <FaTruckFast className=" fill-white text-4xl" />,
        serviceTitle: "FREE AND FAST DELIVERY",
        serviceDescription: "Free delivery for all orders over $140",
    },
    {
        serviceImg: <FaHeadset className=" fill-white text-4xl" />,
        serviceTitle: "24/7 CUSTOMER SERVICE",
        serviceDescription: "Friendly 24/7 customer support",
    },
    {
        serviceImg: <FaRegCircleCheck className="fill-white  text-4xl " />,
        serviceTitle: "MONEY BACK GUARANTEE",
        serviceDescription: "We reurn money within 30 days",
    },
];

export const people = [
    {
        personImg: person1,
        personName: "John Doe",
        position: "Founder & Chairman",
    },
    {
        personImg: person2,
        personName: "Jane Watson",
        position: "Managing Director",
    },
    {
        personImg: person3,
        personName: "Mike Rose",
        position: "Product Designer",
    },
];

export const socials = [
    {
        name: "Twitter",
        icon: <FaXTwitter />,
    },
    {
        name: "Instagram",
        icon: <FaInstagram />,
    },
    {
        name: "LinkedIn",
        icon: <FaLinkedinIn />,
    },
];

export const footerLinks = [
    {
        title: "Exclusive",
        links: [
            { href: "", label: "Subscribe" },
            { href: "", label: "Get 10% off your first order" },
        ],
    },
    {
        title: "Support",
        links: [
            {
                href: "",
                label: "20 Aurora Compound St., Metro Manila, Marikina, Philippines.",
            },
            { href: "", label: "exclusive@gmail.com" },
            { href: "", label: "+99075-11111-77777" },
        ],
    },
    {
        title: "Account",
        links: [
            { href: "", label: "My Account" },
            { href: "", label: "Login / Register" },
            { href: "", label: "Cart" },
            { href: "", label: "Wishlist" },
            { href: "", label: "Shop" },
            { href: "", label: "" },
        ],
    },
    {
        title: "Quick Link",
        links: [
            { href: "", label: "Privacy Policy" },
            { href: "", label: "Terms Of Use" },
            { href: "", label: "FAQ" },
            { href: "", label: "Contact" },
        ],
    },
    {
        title: "Download App",
        links: [{ href: "", label: "Save $3 with App New User Only" }],
    },
];

export const shopProductsData = [
    {
        id: 1,
        productName: "HAVIT HV-G92 Gamepad",
        productImage: product,
        currentPrice: "$120",
        originalPrice: "$160",
        rating: fiveStar,
        rateCount: "88",
        discountPercentage: "-40%",
        quantity: 1,
        description: `The HAVIT HV-G92 is a gamepad designed for gaming enthusiasts seeking an enhanced gaming experience. This gamepad features a ergonomic design and a comfortable grip, allowing for extended gaming sessions without discomfort.`,
        category: ["Electronics", "Flash Sales", "Gaming"],
        subTotal: 120,
    },
    {
        id: 2,
        productName: "AK-900 Wired Keyboard",
        productImage: product2,
        currentPrice: "$960",
        originalPrice: "$1160",
        rating: fourStar,
        rateCount: "75",
        discountPercentage: "-35%",
        quantity: 1,
        description:
            "K-900 Gaming Keyboard comes with USB Wired. Its cable length is 135cm. This is one kind of Luminescent Gaming Keyboard. This iMICE AK-900 has 104 keys, 100mA with DC 5V voltage. It is one of the perfect choices for gaming at a reasonable price. ",
        category: ["Electronics", "Flash Sales", "Gaming"],
        subTotal: 960,
    },
    {
        id: 3,
        productName: "IPS LCD Gaming Monitor",
        productImage: product3,
        currentPrice: "$370",
        originalPrice: "$400",
        rating: fiveStar,
        rateCount: "99",
        discountPercentage: "-40%",
        quantity: 1,
        description:
            "An in-plane switching (IPS) monitor is a type of LCD (liquid-crystal display) monitor. It's made up of backlighting or a mirror behind a polarizer. These sit behind the liquid with crystals mixed into it. The monitor relies on perfect alignment of the liquid crystals to pass along the light to the next polarizer.",
        category: ["Electronics", "Flash Sales", "Computers", "Gaming"],
        subTotal: 370,
    },
    {
        id: 4,
        productName: "S-Series Comfort Chair ",
        productImage: product4,
        currentPrice: "$375",
        originalPrice: "$400",
        rating: fourHalfStar,
        rateCount: "99",
        discountPercentage: "-25%",
        quantity: 1,
        description:
            "The S Series chair combines ergonomic adjustments with a sleek design from Denmark. The armrests, seat height, seat depth, and tilt help you maintain optimal posture, and the high-density internet back provides warmth so you can focus on the tasks at hand.",
        category: ["Home & Lifestyle", "Flash Sales"],
        subTotal: 375,
    },
    {
        id: 5,
        productName: "The north coat",
        productImage: product5,
        currentPrice: "$260",
        originalPrice: "",
        rating: fiveStar,
        rateCount: "65",
        discountPercentage: "",
        quantity: 1,
        description:
            "The North jacket is made from a low-noise, very soft fabric, making a stylish shell garment, with a windproof and waterproof membrane to protect you from the rain and cold. It is accompanied by a thick fleece that can be zipped into the jacket or removed, depending on the weather and how active you are.",

        category: ["Women's Fashion", "Best Selling Products"],
        subTotal: 260,
    },
    {
        id: 6,
        productName: "Gucci duffle bag",
        productImage: product6,
        currentPrice: "$960",
        originalPrice: "",
        rating: fourHalfStar,
        rateCount: "65",
        discountPercentage: "",
        quantity: 1,
        description:
            "Incredibly malleable, this large duffle is made in soft GG Supreme, a softer version of GG Supreme canvas, crafted from a coated microfiber fabric with the GG motif. Comes with a removable Web shoulder strap.",
        category: ["Women's Fashion", "Best Selling Products"],

        subTotal: 960,
    },
    {
        id: 7,
        productName: "RGB liquid CPU Cooler",
        productImage: product7,
        currentPrice: "$160",
        originalPrice: "",
        rating: fourHalfStar,
        rateCount: "65",
        discountPercentage: "",
        quantity: 1,
        description:
            "RGB liquid CPU Cooler is a series of durable CPU liquid coolers designed for mid-sized gaming builds. Each cooler brings the performance, features and design needed to be an essential part of your gaming system. ",
        category: "Electronics",
        subTotal: 160,
    },
    {
        id: 8,
        productName: "Small BookSelf",
        productImage: product8,
        currentPrice: "$360",
        originalPrice: "",
        rating: fiveStar,
        rateCount: "65",
        discountPercentage: "",
        quantity: 1,
        description:
            "This item Small Bookshelf for Small Spaces, 3 Tier Book Shelf Organizer, Wooden Narrow Bookcase, Short Bookshelf for Bedroom, Living Room, Home, Office, Dark Brown",

        category: ["Home & Lifestyle", "Best Selling Products"],
        subTotal: 360,
    },
    {
        id: 9,
        productName: "Breed Dry Dog Food",
        productImage: product9,
        currentPrice: "$100",
        originalPrice: "",
        rating: threeStar,
        rateCount: "35",
        discountPercentage: "",
        quantity: 1,
        description:
            "It is made of ground up ingredients, including meat, grains, legumes, vegetables, and fruits. These ingredients are mixed, shaped into pellets, and then cooked in a process called extrusion",
        category: ["Groceries & Pets", "Best Selling Products"],
        subTotal: 100,
    },
    {
        id: 10,
        productName: "CANON EOS DSLR Camera",
        productImage: product10,
        currentPrice: "$360",
        originalPrice: "",
        rating: fourStar,
        rateCount: "95",
        discountPercentage: "",
        quantity: 1,
        description:
            "Canon EOS (Electro-Optical System) is an autofocus single-lens reflex camera (SLR) and mirrorless camera series produced by Canon Inc. Introduced in 1987 with the Canon EOS 650, all EOS cameras used 35 mm film until October 1996 when the EOS IX was released using the new and short-lived APS film.",
        category: ["Electronics", "Camera"],
        subTotal: 360,
    },
    {
        id: 11,
        productName: "ASUS FHD Gaming Laptop",
        productImage: product11,
        currentPrice: "$700",
        originalPrice: "",
        rating: fiveStar,
        rateCount: "325",
        discountPercentage: "",
        quantity: 1,
        description:
            "Asus has packed its high-end laptops with its Nebula HDR Mini-LED display this year. That means excellent contrast, vivid colors, and slick attention to detailing. This is one of the best laptop screens we've come across, and paired with a silky smooth 240Hz refresh rate there's plenty to love.",
        category: ["Electronics", "Computers"],
        subTotal: 700,
    },
    {
        id: 12,
        productName: "Curology Product Set ",
        productImage: product12,
        currentPrice: "$500",
        originalPrice: "",
        rating: fourStar,
        rateCount: "145",
        discountPercentage: "",
        quantity: 1,
        description:
            "The set includes a promo for a 30 day trial of a tailored formula. This is such a cute set for anyone interested in Curology. There's a gentle cleanser, gel moisturizer, and hydrocoloid patches. I think this would be perfect for those who don't like heavy products.",
        category: "Health & Beauty",
        subTotal: 500,
    },
    {
        id: 13,
        productName: "Kids Electric Car",
        productImage: product13,
        currentPrice: "$960",
        originalPrice: "",
        rating: fiveStar,
        rateCount: "65",
        discountPercentage: "",
        quantity: 1,
        description: `An electric vehicle is a vehicle that uses electricity to move. Its wheels are driven by electric motors. Electric vehicles were one of the first kinds that did not use horse or human power.`,
        category: "Baby's & Toys",
        subTotal: 960,
    },
    {
        id: 14,
        productName: "Jr. Zoom Soccer Cleats",
        productImage: product14,
        currentPrice: "$1160",
        originalPrice: "",
        rating: fiveStar,
        rateCount: "35",
        discountPercentage: "",
        quantity: 1,
        description:
            "Pull tabs and dual straps combine for an easy-on design that eliminates the need for laces and helps get you on the pitch fast. Plus, a Zoom Air unit adds extra comfort and bounce to a variety of fields—from real grass to artificial grass.",
        category: "Sports & Outdoor",
        subTotal: 1160,
    },
    {
        id: 15,
        productName: "GP11 Shooter USB Gamepad",
        productImage: product15,
        currentPrice: "$660",
        originalPrice: "",
        rating: fourHalfStar,
        rateCount: "55",
        discountPercentage: "",
        quantity: 1,
        description:
            "Fantech GP11 Shooter USB Gamepad is best for Gaming like PC and PS3. This gamepad comes with ergonomic shape & weight favored by esports athletes like – Play In Comfort, Feel Comfortable in your hands for hours of gaming, Feel The Action and vibration feedback gives you a riveting gaming experience.",
        category: ["Electronics", "Gaming"],
        subTotal: 660,
    },
    {
        id: 16,
        productName: "Quilted Satin Jacket",
        productImage: product16,
        currentPrice: "$660",
        originalPrice: "",
        rating: fourHalfStar,
        rateCount: "55",
        discountPercentage: "",
        quantity: 1,
        description:
            "Quilted satin bomber jacket with a ribbed stand-up collar, zip down the front, zipped side pockets and ribbing at the cuffs and hem. Jersey lining.",
        category: "Men's Fashion",
        subTotal: 660,
    },
];

export const billingDetails = [
    {
        id: "name",
        label: "Name",
        type: "text",
    },
    {
        id: "street",
        label: "Street Address",
        type: "text",
    },
    {
        id: "apartment",
        label: "Apartment, floor, etc. (optional)",
        type: "text",
    },
    {
        id: "city",
        label: "Town/City",
        type: "text",
    },
    {
        id: "phone",
        label: "Phone Number",
        type: "number",
    },
    {
        id: "email",
        label: "Email Address",
        type: "email",
    },
];
